version: "3" ## especifica a versão do docker-compose file

networks:
  shared-services:
    external: true

services: ## Define um serviço
  catalog: ## nome do serviço
    build: . ## localização do dockerfile
    command: npm run dev ## comando a executar
    ports:
      - "3001:80" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    volumes:
      - .:/app ## monitoro a pasta atual . e envio as alterações para /app
    networks:
      - shared-services