version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  catalog: ## nome do serviço
    build: . ## localização do dockerfile
    command: npm run dev ## comando a executar
    ports:
      - "3000:80" ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 3000
    volumes:
      - .:/usr/app ## monitoro a pasta atual . e envio as alterações para /usr/app